name: Node

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

env:
  ARTIFACTS_DIR: ${{ vars.ARTIFACTS_DIR || 'artifacts' }}
  ARTIFACT_FIREFOX_FILENAME: ${{ vars.ARTIFACT_FIREFOX_FILENAME || 'aria2-integration-firefox.zip' }}
  ARTIFACT_CHROMIUM_FILENAME: ${{ vars.ARTIFACT_CHROMIUM_FILENAME || 'aria2-integration-chromium.zip' }}
  ARTIFACT_ARCHIVE_FILENAME: ${{ vars.ARTIFACT_ARCHIVE_FILENAME || 'aria2-integration-src.zip' }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      attestations: write
    steps:
      - name: Clone repository
        uses: actions/checkout@v7.0.1

      - name: Setup Node.js
        uses: actions/setup-node@v7.0.0
        with:
          node-version-file: .nvmrc
          cache: npm

      - name: Install dependencies
        run: npm install

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm run test

      - name: Create artifacts directory
        run: mkdir "$ARTIFACTS_DIR"

      - name: Build Firefox extension
        run: npm run build:firefox

      - name: Package Firefox extension
        run: cd dist && zip -r "../$ARTIFACTS_DIR/$ARTIFACT_FIREFOX_FILENAME" .

      - name: Upload Firefox artifact
        uses: actions/upload-artifact@v7.0.1
        with:
          name: aria2-integration-firefox
          path: ${{ env.ARTIFACTS_DIR }}/${{ env.ARTIFACT_FIREFOX_FILENAME }}

      - name: Build Chromium extension
        run: npm run build:chromium

      - name: Package Chromium extension
        run: cd dist && zip -r "../$ARTIFACTS_DIR/$ARTIFACT_CHROMIUM_FILENAME" .

      - name: Upload Chromium artifact
        uses: actions/upload-artifact@v7.0.1
        with:
          name: aria2-integration-chromium
          path: ${{ env.ARTIFACTS_DIR }}/${{ env.ARTIFACT_CHROMIUM_FILENAME }}

      - name: Attest artifacts
        uses: actions/attest@v4.2.2
        with:
          subject-path: |
            ${{ env.ARTIFACTS_DIR }}/${{ env.ARTIFACT_FIREFOX_FILENAME }}
            ${{ env.ARTIFACTS_DIR }}/${{ env.ARTIFACT_CHROMIUM_FILENAME }}
  release:
    name: Release
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v7.0.1

      - name: Setup Node.js
        uses: actions/setup-node@v7.0.0
        with:
          node-version-file: .nvmrc

      - name: Download Firefox artifact
        uses: actions/download-artifact@v8.0.1
        with:
          name: aria2-integration-firefox
          path: ${{ env.ARTIFACTS_DIR }}

      - name: Download Chromium artifact
        uses: actions/download-artifact@v8.0.1
        with:
          name: aria2-integration-chromium
          path: ${{ env.ARTIFACTS_DIR }}

      - name: Verify artifacts
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh attestation verify "$ARTIFACTS_DIR/$ARTIFACT_FIREFOX_FILENAME" --repo ${{ github.repository }}
          gh attestation verify "$ARTIFACTS_DIR/$ARTIFACT_CHROMIUM_FILENAME" --repo ${{ github.repository }}

      - name: Archive repository
        run: git archive --format zip --output "$ARTIFACTS_DIR/$ARTIFACT_ARCHIVE_FILENAME" ${{ github.ref_name }}

      - name: Release Firefox extension
        uses: baptistecdr/release-firefox-addon@main
        if: ${{ vars.RELEASE_FIREFOX_EXTENSION == 'true' }}
        with:
          addon-id: ${{ secrets.MOZILLA_ADDONS_ADDON_ID }}
          auth-api-issuer: ${{ secrets.MOZILLA_ADDONS_API_KEY }}
          auth-api-secret: ${{ secrets.MOZILLA_ADDONS_API_SECRET }}
          addon-path: ${{ env.ARTIFACTS_DIR }}/${{ env.ARTIFACT_FIREFOX_FILENAME }}
          source-path: ${{ env.ARTIFACTS_DIR }}/${{ env.ARTIFACT_ARCHIVE_FILENAME }}
          compatibility: 'firefox,android'
          release-note: 'Release ${{ github.ref_name }}'

      - name: Release Microsoft Edge extension
        uses: baptistecdr/release-edge-extension@v2.1.0
        if: ${{ vars.RELEASE_EDGE_EXTENSION == 'true' }}
        with:
          api-key: ${{ secrets.MS_API_KEY }}
          client-id: ${{ secrets.MS_API_CLIENT_ID }}
          product-id: ${{ secrets.MS_API_PRODUCT_ID }}
          product-path: ${{ env.ARTIFACTS_DIR }}/${{ env.ARTIFACT_CHROMIUM_FILENAME }}

      - name: Release Chrome extension
        uses: baptistecdr/release-chrome-extension@v2.0.3
        if: ${{ vars.RELEASE_CHROME_EXTENSION == 'true' }}
        with:
          extension-id: ${{ secrets.GOOGLE_API_EXTENSION_ID }}
          extension-path: ${{ env.ARTIFACTS_DIR }}/${{ env.ARTIFACT_CHROMIUM_FILENAME }}
          oauth-client-id: ${{ secrets.GOOGLE_API_CLIENT_ID }}
          oauth-client-secret: ${{ secrets.GOOGLE_API_CLIENT_SECRET }}
          oauth-refresh-token: ${{ secrets.GOOGLE_API_REFRESH_TOKEN }}
