name: Release

on:
  workflow_dispatch:
    inputs:
      version-type:
        description: Version type to release
        required: true
        type: choice
        options:
          - major
          - minor
          - patch

jobs:
  release:
    name: Release ${{ inputs.version-type }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Clone repository
        uses: actions/checkout@v6
        with:
          token: ${{ secrets.RELEASE_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: .nvmrc
          cache: npm

      - name: Set ${{ inputs.version-type }} version
        id: release_version
        run: |
          RELEASE_VERSION=$(npm version --no-git-tag-version --no-commit-hooks ${{ inputs.version-type }})
          node scripts/update-manifest-version.js $RELEASE_VERSION
          npm install --package-lock-only
          npm run lint:fix
          echo "RELEASE_VERSION=$RELEASE_VERSION" >> $GITHUB_OUTPUT

      - name: Commit, push and create tag
        uses: EndBug/add-and-commit@v9
        with:
          fetch: true
          default_author: github_actions
          message: Release ${{ steps.release_version.outputs.RELEASE_VERSION }}
          pathspec_error_handling: exitImmediately
          push: true
          tag: ${{ steps.release_version.outputs.RELEASE_VERSION }}

      - name: Create release
        env:
          GH_TOKEN: ${{ github.token }}
        run: gh release create ${{ steps.release_version.outputs.RELEASE_VERSION }} --generate-notes

      - name: Set next dev version
        id: dev_version
        run: |
          DEV_VERSION=$(npm version --no-git-tag-version --no-commit-hooks --preid SNAPSHOT prerelease)
          node scripts/update-manifest-version.js $DEV_VERSION
          npm install --package-lock-only
          npm run lint:fix
          echo "DEV_VERSION=$DEV_VERSION" >> $GITHUB_OUTPUT

      - name: Commit and push
        uses: EndBug/add-and-commit@v9
        with:
          fetch: true
          default_author: github_actions
          message: Set next dev version to ${{ steps.dev_version.outputs.DEV_VERSION }}
          pathspec_error_handling: exitImmediately
          push: true
